services:
  - type: web
    name: frontend_namaste_wellness
    env: static
    buildCommand: cd ui; yarn install --production=false; yarn build
    staticPublishPath: ui/build/
    buildFilter:
      paths:
        - ui/**/*.js
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
  - type: web
    name: backend_namaste_wellness
    plan: free
    env: node
    buildCommand: cd api; yarn
    startCommand: cd api; yarn start
    buildFilter:
      paths:
        - api/**/*.js
databases:
  - name: database_namaste_wellness
    plan: free
    databaseName: namaste
    ipAllowList: [] # only allow internal connections
