services:
  - type: web
    name: front_namaste_wellness
    env: static
    buildCommand: cd ui; yarn install --production=false; yarn build
    staticPublishPath: ui/build/
    buildFilter:
      paths:
        - ui/**/*.js
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
  - type: web
    name: namaste_wellness
    plan: free
    env: node
    buildCommand: cd api; yarn, npx knex migrate:latest , npx knex seed:run --specific=seed-3.quotes.js
    startCommand: cd api; yarn run prod
    buildFilter:
      paths:
        - api/**/*.js
databases:
  - name: database_namaste_wellness
    plan: free
    databaseName: namaste
    ipAllowList: [] # only allow internal connections
